### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by season1blue** [LorrinWWW/two-are-better-than-one#1]
hi, thanks for your work
Is the code available now?
or does its dataset need any special processing skills?

**Comment by LorrinWWW** [comment]
Sorry to be late, I am too busy these days. The datasets use standard preprocessing methods according to previous work (means, it should not depend on any special processing skills). We cannot directly release the processed ACE datasets due to the copyright issue, so we need to polish the preprocessing script. We will update this part after the EMNLP's video upload deadline. Before that, I am also glad to answer any question about the code.

**Comment by LorrinWWW** [comment]
Scripts updated. Feel free to reopen the issue if you have other questions.
