### ISSUE TITLE
Not enough memory when i do `python gens/gen_bert.py` on MY OWN DATASET

### ISSUE THREAD

**Issue by LimKim** [LorrinWWW/two-are-better-than-one#15]
train.CoNLL04.json  under the path  datasets/unified/  is 352KB, and I can run gens/gen_bert.py on this dataset.
But when I run the script on my own dataset(train.xx.json is 39MB),  the device memory can't hold on and be killed finially.

How to solve this problem?
Thanks.

**Comment by LorrinWWW** [comment]
There are mainly two options:

First one, do not pre-generate the BERT embeddings, instead, pass the huggingface style language model address (e.g., bert-base-uncased) to "--lm_emb_path". 
This will load the BERT model and generate BERT embeddings online.
But it also means that the training will become slower and it will consume more GPU memory (but that is irrelevant to dataset size).

Second one, you may need to modify the process of reading BERT embeddings, so the system do not have read all BERT embeddings into memory. For example, use lightweight key-value databases instead of python dict (current one) to store BERT embeddings.

**Comment by LimKim** [comment]
> There are mainly two options:
> 
> First one, do not pre-generate the BERT embeddings, instead, pass the huggingface style language model address (e.g., bert-base-uncased) to "--lm_emb_path".
> This will load the BERT model and generate BERT embeddings online.
> But it also means that the training will become slower and it will consume more GPU memory (but that is irrelevant to dataset size).
> 
> Second one, you may need to modify the process of reading BERT embeddings, so the system do not have read all BERT embeddings into memory. For example, use lightweight key-value databases instead of python dict (current one) to store BERT embeddings.

Thank you very much!
