### ISSUE TITLE
Segfault when getting embedding

### ISSUE THREAD

**Issue by zeyofu** [LorrinWWW/two-are-better-than-one#2]
<img width="803" alt="Screen Shot 2020-11-03 at 6 10 53 PM" src="https://user-images.githubusercontent.com/31453585/98050545-eae9f800-1dff-11eb-83ee-74dfc85933e4.png">
Hi, I get segmentation fault when I try to run gen_bert.py. Is there anyone else having the issue?

**Comment by LorrinWWW** [comment]
Sorry for the late reply. But I cannot reproduce the error. Did you install the correct version of dependencies? Could it be the memory issue (since all generated embeddings will be temporarily stored in the memory)? Does the progress bar appear, i.e., does the error occur in the middle of embeddings generation process?

**Comment by zeyofu** [comment]
If I don't use the head attention it would work just find. It should be because of the version of my allenNLP.
