### ISSUE TITLE
AllenNLP version

### ISSUE THREAD

**Issue by lehgtrung** [LorrinWWW/two-are-better-than-one#27]
Hi, can you tell the version of AllenNLP that you are using in this project. When I install the newest version of AllenNLP, it keeps overriding pytorch and transformer version. Thanks.

**Comment by LorrinWWW** [comment]
Hi, I'm sorry I am not very sure about the exact version of allennlp currently, but I will look into this and tell you later.
However, since we only used its CRF implementation and we do not enable CRF by default, you can simply ignore this dependency. 
(I have updated the code so it would raise an exception when trying to import CRF from allennlp)

**Comment by LorrinWWW** [comment]
Quick update: The version of allennlp should be 0.9.0. I will recommend to leave it along as we do not need CRF for this project.

**Comment by lehgtrung** [comment]
@LorrinWWW Thank you so much for your help, I pulled new code and it didn't require AllenNLP anymore.
